"""add picture_url to Planet

Revision ID: 5f15209f0173
Revises: 83036308a26b
Create Date: 2023-03-27 21:00:35.006058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f15209f0173'
down_revision = '83036308a26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=260), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
